targets/aws: targets/aws/**
targets/bash: targets/bash/**
targets/brew: targets/brew/**
targets/chamber: targets/chamber/**
targets/completion: targets/completion/**
targets/compose: targets/compose/**
targets/direnv: targets/direnv/**
targets/docker: targets/docker/**
targets/docs: targets/docs/**
targets/git: targets/git/**
targets/gitleaks: targets/gitleaks/**
targets/helm: targets/helm/**
targets/helmfile: targets/helmfile/**
targets/make: targets/make/**
targets/packages: targets/packages/**
targets/readme: targets/readme/**
targets/semver: targets/semver/**
targets/slack: targets/slack/**
targets/template: targets/template/**
