
## run manifest/pull followed by manifest/make
manifest: manifest/pull manifest/make

## clone or update manifest repos to \$REPO_PATH"
manifest/pull:
	@manifest pull

## initialize local manifest repos by calling their default make target
manifest/make:
	@manifest make 
